print("Hello, it's nice to you.")
print("Welcome to Kali's.") 
print("What is your name? ")
myname = input()
print(f"Hello {myname}, it's nice to meet you.")
print("How old are you.")
age = input()
print(f"{myname} are you really {age}. Wow you look great!")
print("Can I call you? What is your number?")
number = input()
print(f"Great,I'll call you at {number}")
